// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxeEDcb4dawIShu_bQVsMrut2PQebjBlA',
    appId: '1:321272147906:web:c939a03b445acd9731305b',
    messagingSenderId: '321272147906',
    projectId: 'rptest-ebb20',
    authDomain: 'rptest-ebb20.firebaseapp.com',
    storageBucket: 'rptest-ebb20.firebasestorage.app',
    measurementId: 'G-QWE5XXN84D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvM6SKFrSmfWZwbRPEHkDbCv6hOUck9kI',
    appId: '1:321272147906:android:726ac32415b3e96631305b',
    messagingSenderId: '321272147906',
    projectId: 'rptest-ebb20',
    storageBucket: 'rptest-ebb20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaDhS4IV5Xsh9NmTKV7mR5Z7SKU1bi-Rs',
    appId: '1:321272147906:ios:e3fab73ee6e9c5d131305b',
    messagingSenderId: '321272147906',
    projectId: 'rptest-ebb20',
    storageBucket: 'rptest-ebb20.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );
}
